name: Run Existing Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Pull Docker image
      run: |
        docker pull kunalgawande/speech_to_text:0.2

    - name: Run Docker container
      run: |
        docker run -d --name speech_to_text_container \
        --gpus=all \
        -v /home/vikas/kunal:/env \
        -p 8080:8888 \
        -p 8000:8000 \
        --shm-size=2g \
        kunalgawande/speech_to_text:0.2

    - name: List running Docker containers
      run: |
        docker ps

